# Generated by Django 4.0.5 on 2022-06-17 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.CharField(max_length=255, unique=True)),
                ('zoneLocation', models.CharField(max_length=255, unique=True)),
                ('zoneOccupants', models.IntegerField(default=0)),
                ('zoneCreationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('zoneAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachersNum', models.IntegerField(default=0)),
                ('studentsNum', models.IntegerField(default=0)),
                ('schlName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.hood')),
            ],
        ),
        migrations.CreateModel(
            name='policeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officers', models.IntegerField(default=0)),
                ('stationName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.hood')),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorsNum', models.IntegerField(default=0)),
                ('nursesNum', models.IntegerField(default=0)),
                ('hName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.hood')),
            ],
        ),
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bizName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.hood')),
            ],
        ),
    ]
