# Generated by Django 4.0.5 on 2022-06-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
