# Generated by Django 4.0.5 on 2022-06-17 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_name_school_schlname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('profileImage', models.ImageField(default='default.png', upload_to='projectPics')),
                ('bio', models.TextField(blank=True, default='The Zone Community', max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('idNum', models.IntegerField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hood')),
            ],
        ),
    ]
